[package]
name = "fluid-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2d"
path = "src/2d.rs"

[[bin]]
name = "3d"
path = "src/3d.rs"

[dependencies]
crossbeam-channel = "0.5"
crossterm = "0.29"
glam = "0.30"
rand = "0.9"
