[package]
name = "fluid-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "2d_multi"
path = "src/2d_multi.rs"

[[bin]]
name = "3d_multi"
path = "src/3d_multi.rs"

[dependencies]
ahash = "0.8"
crossbeam-channel = "0.5"
crossterm = "0.29"
glam = "0.30"
rand = "0.9"
rayon = "1"
